-- Run this script in your Supabase SQL Editor

-- Drop existing tables to ensure a clean slate if you are re-running this script
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS notes CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;

-- 1. Create Teachers Profile Table (Links to Supabase Auth)
CREATE TABLE teachers (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
    name TEXT,
    email TEXT,
    dept TEXT,
    role TEXT,
    univ TEXT,
    initials TEXT,
    tutorial_done INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Create Courses Table
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id UUID REFERENCES teachers(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    code TEXT,
    semester TEXT,
    room TEXT,
    icon TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Create Students Table
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    roll TEXT,
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Create Attendance Table
CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    lecture_no INTEGER NOT NULL,
    status TEXT NOT NULL,
    note TEXT,
    date TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Create Notes Table
CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id UUID REFERENCES teachers(id) ON DELETE CASCADE,
    title TEXT,
    content TEXT,
    color TEXT,
    pinned INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Create Materials Table
CREATE TABLE materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id UUID REFERENCES teachers(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES courses(id) ON DELETE SET NULL,
    title TEXT,
    filename TEXT NOT NULL,
    original_name TEXT NOT NULL,
    file_size BIGINT,
    file_type TEXT,
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (Important!)
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE materials ENABLE ROW LEVEL SECURITY;

-- Add RLS Policies so users can only see their own data
CREATE POLICY "Users can view own profile" ON teachers FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON teachers FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON teachers FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can do all to own courses" ON courses FOR ALL USING (auth.uid() = teacher_id);

CREATE POLICY "Users can do all to own students" ON students FOR ALL USING (EXISTS (SELECT 1 FROM courses WHERE courses.id = students.course_id AND courses.teacher_id = auth.uid()));

CREATE POLICY "Users can do all to own attendance" ON attendance FOR ALL USING (EXISTS (SELECT 1 FROM courses WHERE courses.id = attendance.course_id AND courses.teacher_id = auth.uid()));

CREATE POLICY "Users can do all to own notes" ON notes FOR ALL USING (auth.uid() = teacher_id);

CREATE POLICY "Users can do all to own materials" ON materials FOR ALL USING (auth.uid() = teacher_id);

-- Also, configure Storage:
-- 1. Go to "Storage" in Supabase dashboard
-- 2. Create a new bucket named "materials"
-- 3. Set policies to allow authenticated users to upload/download.
